sudo:
  false

addons:
  postgresql: '9.4'
  sauce_connect: true

language:
  python

python:
  - 3.5

services:
  - postgresql
  - redis-server

env:
  global:
    - TESTING=True
    - TEST_DATABASE_URL=postgres://postgres@localhost:5432/goodtables_test

before_install:
  - nvm install 6
  - nvm use 6

install:
  - make install-frontend
  - make install-dev
  - psql -c 'create database goodtables_test;' -U postgres
  - make frontend

script:
  - cp .env.example .env
  - make test

after_success:
  - pip install coveralls
  - coveralls

cache:
  directories:
    - $HOME/.cache/pip
